global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8081']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 