apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
      - name: user-interface
        image: mohammadshaad/user-interface:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-interface
spec:
  selector:
    app: user-interface
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer 